### PR TITLE
:rotating_light: Fix Elixir warning, bump to 0.6.1, update dependencies, & run mix format

### PR DESCRIPTION
**Pull request by jyc**
Hello!

Thanks for making this library. Recent versions of the Elixir compiler complain about a parse ambiguity:

```
==> rustic_result
    warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

    This error happens when you have function calls without parentheses inside keywords. For example:

        function(arg, one: nested_call a, b, c)
        function(arg, one: if expr, do: :this, else: :that)

    In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

        function(arg, one: if(expr, do: :this, else: :that))
        function(arg, one: nested_call(a, b, c))

    Ambiguity found at:
    │
 75 │   def unwrap!({:error, reason}), do: raise UnhandledError, reason: reason
    │   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    │
    └─ lib/rustic_result.ex:75

    warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

    This error happens when you have function calls without parentheses inside keywords. For example:

        function(arg, one: nested_call a, b, c)
        function(arg, one: if expr, do: :this, else: :that)

    In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

        function(arg, one: if(expr, do: :this, else: :that))
        function(arg, one: nested_call(a, b, c))

    Ambiguity found at:
    │
 79 │   def unwrap_err!(:ok), do: raise MissingError, value: nil
    │   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    │
    └─ lib/rustic_result.ex:79

    warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

    This error happens when you have function calls without parentheses inside keywords. For example:

        function(arg, one: nested_call a, b, c)
        function(arg, one: if expr, do: :this, else: :that)

    In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

        function(arg, one: if(expr, do: :this, else: :that))
        function(arg, one: nested_call(a, b, c))

    Ambiguity found at:
    │
 80 │   def unwrap_err!({:ok, val}), do: raise MissingError, value: val
    │   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    │
    └─ lib/rustic_result.ex:80
```

I made the small changes necessary to:

- fix the parse ambiguity  
- format using `mix format`
- update dependencies
- bump the version to 0.6.1

`mix test` succeeds.

### CODE REVIEW

**Review by linkdd — CHANGES_REQUESTED** [review]
Thank you for your PR! I'll have to renew my credentials to publish on 

Though, can you please rebase and use [Gitmoji](https://gitmoji.dev) for the commit messages? And drop the `mix format` commit as well, I don't really adhere to its default code-style and haven't took the time to configure it properly to my tastes ^^"

Thank you :)

**Comment by jyc** [comment]
np!

> Though, can you please rebase

do you mean you'd prefer the commits to be squashed? I checked and it looks like my branch is based on your main branch already

> and use [Gitmoji](https://gitmoji.dev/) for the commit messages?

sure! which gitmoji do you want me to use if the squashed commit combines the version bump, parse ambiguity fix, and dependency update?

> And drop the mix format commit as well, I don't really adhere to its default code-style and haven't took the time to configure it properly to my tastes ^^"

sounds good!

If you'd prefer to do these changes yourself and then merge it in I'm fine with that! Otherwise happy to squash / change the commit message when you let me know what you want it to say

**Comment by linkdd** [comment]
> do you mean you'd prefer the commits to be squashed?

No squash, just rewording the commits to make them use gitmoji :)

**Comment by jyc** [comment]
Ah sure, OK. The term for that is *amending* commits, not [rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing). Will do!

**Comment by jyc** [comment]
Amended the commits and switched to gitmoji! If you need any further changes please feel free to edit my branch. Thanks again for the library!

**Review by linkdd — APPROVED** [review]

**Pull request merged**
